version: 0.2
env:
  variables:
    ECR_REPOSITORY_URI_TAG: 'DefaultUri'
  exported-variables:
    - ECR_REPOSITORY_URI_TAG
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - VERSION=$(cat version.txt)
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:latest -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t $ECR_REPOSITORY_URI:$VERSION .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_REPOSITORY_URI:latest
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG
      - docker push $ECR_REPOSITORY_URI:$VERSION
      - ECR_REPOSITORY_URI_TAG=$ECR_REPOSITORY_URI:$IMAGE_TAG
      - echo ${ECR_REPOSITORY_URI_TAG}
      - echo "Uploading to CHANGELOG ...."
      - aws s3 cp CHANGELOG.md s3://houndoc-changelog/MD/AIForms.md
      - aws cloudfront create-invalidation --distribution-id EIRU1D5WYXMJD --paths "/*"
